---
- name: Check for tomcat on remote box
  stat:
    path: '{{ download_dir }}/{{ art_redis_filename }}'
  register: remote_art_file
  ignore_errors: yes

- name: Create ART Reports home directory
  file:
    path: "{{ art_home_path }}"
    state: directory

- name: Download and extract ART Reports to ART home directory
  unarchive:
    src: "{{ art_archive_url }}/{{ art_archive_name }}{{ art_archive_name_ext }}"
    dest: "{{ art_home_path }}"
    remote_src: true
    group: "{{ tomcat_group }}"
    creates: "{{ art_archive_install_path }}"
  when: not remote_art_file.stat.exists

- name: Extract local ART Reports
  unarchive:
    src: "{{ download_dir }}/{{ art_redis_filename }}"
    dest: "{{ art_home_path }}"
    remote_src: true
    group: "{{ tomcat_group }}"
    creates: "{{ art_archive_install_path }}"
  when: remote_art_file.stat.exists

- name: Create symlink to current version of ART Reports
  block:
      - name: Check for current symlink
        stat:
          path: "{{ art_install_link }}"
        register: current_art_symlink
        ignore_errors: yes

      - name: Symlink ART Reports to current version
        file:
          src: "{{ art_archive_install_path }}"
          dest: "{{ art_install_link }}"
          state: link
        when: art_symlink or not current_art_symlink.stat.exists

      - name: Symlink ART Reports to current version
        debug:
            msg:
                - "Alert! Not creating symlink to current version as requested or this is an upgrade"
                - "To create execute the following command on the host:"
                - "symlink -sfn {{ art_archive_install_path }} {{ art_install_link }}"
        when: not art_symlink and current_art_symlink.stat.exists

- name: Deploy ART Reports to Tomcat
  file:
    src: "{{ art_install_link }}/art.war"
    dest: "{{ tomcat_home_path }}/webapps/art.war"
    state: link

- name: Copy Local ART Reports
  block:
    - name: check for ART Reports on local box
      stat:
        path: '{{ local_archive_dir }}/{{ art_redis_filename }}'
      delegate_to: localhost
      register: art_local_file
      ignore_errors: yes
      become: no
      when: use_local_archive

    - name: create download directory
      file:
        state: directory
        mode: 'u=rwx,go=rx'
        dest: '{{ download_dir }}'
      when: use_local_archive

    - name: copy ART Reports from local box
      copy:
        src: '{{ local_archive_dir }}/{{ art_redis_filename }}'
        dest: '{{ download_dir }}/{{ art_redis_filename }}'
        mode: 'u=rw,go=r'
      when: use_local_archive and art_local_file.stat.exists
  when:
    - use_local_archive
    - art_redis_filename not in (None, '', omit)
