---
# tasks file for tomcat-stig/
- name: Gather OS Type
  setup:
      gather_subset: distribution,!all,!min
  when:
      - ansible_distribution is not defined
  tags:
      - always

- name: Include Prelim Tasks
  import_tasks: prelim.yml
  tags:
      - prelim_tasks

- name: Install ART Reports
  import_tasks: install_art_reports.yml
  tags:
      - art_install
