---
- name: Find $CATALINA_HOME directory
  shell: cat /etc/systemd/system/tomcat.service | grep "CATALINA_HOME" | cut -f3 -d= | tr -d '"'
  changed_when: false
  register: catalina_find_home_dir

- name: Install needed packages
  block:
      - name: Install RHEL7 based packages
        yum:
            name: ['python-lxml', 'python-crypto']
            state: present
        when:
            - ansible_distribution == "RedHat"
            - ansible_distribution_major_version == "7"

      - name: Install CentOS7 based packages
        yum:
            name: ['python-lxml', 'python-crypto']
            state: present
        when:
            - ansible_distribution == "CentOS"
            - ansible_distribution_major_version == "7"

      - name: Install RHEL8 based packages
        dnf:
            name: ['python3-lxml', 'python3-crypto']
            state: present
        when:
            - ansible_distribution_file_variety == "RedHat"
            - ansible_distribution_major_version == "8"

      - name: Install Ubuntu based packages
        apt:
            name: ['python3-lxml', 'python3-crypto']
            state: present
        when: ansible_distribution_file_variety == "Debian" and ansible_distribution_major_version == "16" or ansible_distribution_major_version == "18" or ansible_distribution_major_version == "20"

- name: Install Tomcat
  include_tasks: install_tomcat.yaml
  when:
    - tcat_install